### PR TITLE
Updated views taxonomy term name depth patch

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Update the patch used to work with percona database.

# Need Review By (Date)
- soon

# Urgency
- high

# Steps to Test
1. Review the patch and the interdiff https://www.drupal.org/project/views_taxonomy_term_name_depth/issues/2877249#comment-13996836

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
That sql-sync command wasn't directly related to this issue and so it's not solved by this PR. By syncing that `ceedrupal8` site i was able to find a different issue that should be solved by this.

**Comment by mdyoung3** [comment]
So, this solves the duplicate row in the search table?

**Comment by pookmish** [comment]
No. this solves the subquery issue with percona. the duplicate row with the subscripts is still present but its for another time.

**Comment by mdyoung3** [comment]
Gotcha.

**Review by imonroe — APPROVED** [review]
Looks ok to me.

**Pull request merged**
