### PR TITLE
D8CORE-4667: change to full month from an abbreviation 

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- in a screen reader only tag, I changed the abbreviated month to the full month.

# Review By (Date)
- 8/28

# Criticality
- Med
- Events module

# Urgency
- Normal
- Accessibility fix

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to the Events list page
4. Verify that the `<div class="sr-only">` has the full month and not an abbreviation. Look at single day and multi-day event. 
5. What it was:
6. 
image
7. What it should be:
8. 
image

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? : NO

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [x] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- D8CORE-4667
- @cjwest 

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by pookmish** [comment]
I'm wondering... why do we need to have something for the screen reader on this part. We are basically duplicating the information that is already available. 
@cjwest should we just remove this `sr-only` piece to reduce duplicated information?

**Comment by cjwest** [comment]
@pookmish,
Yes, we could do it that way as well.

**Comment by jenbreese** [comment]
@cjwest @pookmish Ok, I removed the `sr-only` and tested on Voiceover. I could still hear the date from the block of content. Thanks!

**Review by pookmish — APPROVED** [review]
Cool. less complications :smile:

**Pull request merged**
