### PR TITLE
D8CORE-2306: removed sorting controls in the event schedule entity reference field.

### PR DESCRIPTION
**Pull request by imonroe**
# READY FOR REVIEW

# Summary
- UX update for events admin.
- Removes the row weight and drag 'n drop sorting for event schedules.

# Review By (Date)
- 11/5/2020

# Criticality
- 2 of 5

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. create an event that has a schedule.
3. Add some things to the schedule.  Notice there's no row weights or drag-n-drop reordering.
4. Save the event. Notice the schedule is sorted based on times.

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/D8CORE-2306

### CODE REVIEW

**Comment by sherakama** [comment]
This looks fine to me but the view still "sorts" them by date. Do we also want to remove the date sorting on the view or this is fine?

**Comment by pookmish** [comment]
Why wouldn't we just display them field items as the user sorts them. it would reduce the need for this and the view wouldn't really be needed at that point.

**Comment by imonroe** [comment]
I was going off what was in the ticket; it says the decision was made to remove the controls and to allow the view to sort it by date, which was the expected behavior.

**Comment by pookmish** [comment]
I would like to revisit that discussion. "not intuitive" is still a problem with this implementation. Because a user doesn't have the ability to change the order, but they still have no way to choose the order of the items. If we wan't the order to be intuitive, it would probably be best to remove the sorting entirely and allow a user to drag and drop as they see fit.

**Comment by pookmish** [comment]
I just spoke to Ishi and she's good with the approach of retaining the drag and drop but removing the sorting on the display of the schedule.

**Comment by sherakama** [comment]
> I just spoke to Ishi and she's good with the approach of retaining the drag and drop but removing the sorting on the display of the schedule.

That might be complicated as well as there is grouping on the view. Schedule items are grouped together when then have the same date so what happens when to items of the same date are in different parts of the order?

**Comment by imonroe** [comment]
I think we need to talk about this more.  Grouping in the view based on the chronological order of the schedule makes perfect sense. I'm having a harder time thinking of why arbitrary sorting based on the row weight makes more sense.  I'm happy to do it either way, but it'd be great to have some consensus.  This is a UX improvement, not a bug fix, so it's not critical to the release.

**Comment by sherakama** [comment]
TBH, I'd vote to just leave it as is but we should have a 15-minute chat to discuss.

**Comment by imonroe** [comment]
invite sent for this afternoon

**Review by pookmish — APPROVED** [review]

**Pull request merged**
