### PR TITLE
D8CORE-2317: fix to the missing location on events

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- Missing location fix

# Review By (Date)
- 7/7

# Criticality
- Critical
- All sites with Events on D8

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to Events list. Add an event and add an address. Please fill in all fields. Add one for US and another country.
3. Verify the list and filtered list has the address displayed.

## Front End Validation
- [x] Is the markup using the appropriate semantic tags and passes HTML validation?
- [x] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- This effects the Events module.
- https://github.com/SU-SOE/soe_profile/pull/44
- https://github.com/SU-SWS/stanford_profile/pull/251

# Associated Issues and/or People
- D8CORE=2317
- We weren't getting addresses added into the content type on the list page. The imported ones were working so you'd see the Zooms or Online notes.
- **IMPORTANT NOTE:** with config files do we need to put them in for the SOE, Module and the Stanford_helper? Is one concerned the source that they all trickle out too?

### CODE REVIEW

**Comment by imonroe** [comment]
I notice that when the address shows up in the address list, there are some issues with the way it's displayed, if all the fields are filled out:

image

I think we should consider a line break in the case where there is a company name.  Also, if we're putting the address all on a single line, I think the commas should not have the leading space before them.

**Comment by jenbreese** [comment]
In the design, it has the address in one line with commas for the address and spacing after the company name. I can show Ishi for feedback too. 
Screen Shot 2020-07-07 at 11 57 02 AM

**Comment by jenbreese** [comment]
Hi @imonroe, I went back to fix these conflicts and had to redo some work. It's pretty late here so really late there. Sorry about that.

**Comment by imonroe** [comment]
> Hi @imonroe, I went back to fix these conflicts and had to redo some work. It's pretty late here so really late there. Sorry about that.

No worries.  I'm fading, so I'm going to have to test this tomorrow morning.

**Pull request merged**
