### PR TITLE
D8CORE-3161: reduce load more button size

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Changed the Load More button from a button-big to a button-primary
- Moved the SCSS to the Stanford Basic theme.
- Done on People, Events, and News. 
- Publications already had the primary button size but removed the duplicate code.

# Review By (Date)
- 9/8

# Criticality
- Normal
- Affects all sites using or inheriting from the Stanford Basic theme
- @jdwjdwjdw @rebeccahongsf @rmundstock  - FYI

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Create/Generate enough content to get the load more button on the News, Events and People list page
4. Verify the large Load More button is now a regular sized one.
5. Create list paragraphs with the 4 types with a number cap and verify the button is small on the list too.

New
Screen Shot 2021-09-01 at 10 51 40 AM

Old
Screen Shot 2021-09-01 at 10 51 55 AM

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? NO

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Affects all sites using or inheriting from the Stanford Basic theme

# Associated Issues and/or People
- [D8CORE-3161](https://stanfordits.atlassian.net/browse/D8CORE-3161)
- https://github.com/SU-SWS/stanford_person/pull/151
- https://github.com/SU-SWS/stanford_news/pull/132
- https://github.com/SU-SWS/stanford_events/pull/83
- https://github.com/SU-SWS/stanford_basic/pull/242
- https://github.com/SU-SWS/stanford_publication/pull/47
- @jdwjdwjdw @rebeccahongsf @rmundstock  - FYI

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by pookmish** [comment]
Just before I merged this i saw the other 3 identical PRs. Should we just generalize it and throw it into `stanford_basic`?

**Comment by jenbreese** [comment]
I'm not sure. If it isn't there for News (I think) the button is just a link. Should the modules be pretty close to stand alone without the Stanford Basic theme?

**Comment by pookmish** [comment]
The modules can be "good enough". we could remove the styling from the module and move it to a more generalized location.

I'm toying with the idea of a `stanford_profile_theme` so that we can just move everything to that one location and deprecate all of the styles in the modules (or move them to a submodule)

**Comment by jenbreese** [comment]
In that case I think it is a good idea.  It is 3x the same code.

**Review by pookmish — APPROVED** [review]

**Pull request merged**
